# Generated by Django 3.1.1 on 2020-09-08 23:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('documento', models.CharField(blank=True, help_text='Sin puntos ni guión', max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100, null=True)),
                ('segundo_apellido', models.CharField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today, help_text='ej. 01/08/2012', verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(blank=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Número debe ser ingresado en formato '09XXXXXXX'.", regex='^\\?09?\\d{9}$')], verbose_name='Número de teléfono celular')),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('nucleo_activo', models.BooleanField(default=True)),
                ('relacion_nucleo', models.CharField(choices=[('TITULAR', 'TITULAR'), ('CONYUGE', 'CONYUGE'), ('MADRE', 'MADRE'), ('PADRE', 'PADRE'), ('HIJO', 'HIJO')], default='TITULAR', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tipo', models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('SECRETARIA', 'SECRETARIA'), ('PACIENTE', 'PACIENTE')], default='PACIENTE', max_length=15)),
                ('user_direccion', models.CharField(max_length=155, null=True)),
                ('user_celular', models.IntegerField(null=True)),
                ('user_alta', models.DateField(blank=True, null=True)),
                ('user_especialidad', models.CharField(blank=True, choices=[('ORTOPEDIA', 'ORTOPEDIA'), ('ORTODONCIA', 'ORTODONCIA'), ('GENERAL', 'GENERAL')], max_length=15, null=True)),
                ('user_calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion_dental', models.CharField(blank=True, max_length=50, null=True)),
                ('test_dental', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trat_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
    ]
