# Generated by Django 3.1.1 on 2020-09-16 23:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('documento', models.CharField(blank=True, help_text='Sin puntos ni guión', max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100, null=True)),
                ('segundo_apellido', models.CharField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today, help_text='ej. 01/08/2012', verbose_name='Fecha de nacimiento')),
                ('celular', models.CharField(blank=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="El número debe ser del formato: '+XXXXXXXXX'. 9 digitos admitidos.", regex='^\\+?1?\\d{9,9}$')], verbose_name='Número de teléfono celular')),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('nucleo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tipo', models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('SECRETARIA', 'SECRETARIA'), ('PACIENTE', 'PACIENTE')], default='', max_length=15)),
                ('user_direccion', models.CharField(max_length=155, null=True)),
                ('user_celular', models.IntegerField(null=True)),
                ('user_alta', models.DateField(blank=True, null=True)),
                ('user_especialidad', models.CharField(blank=True, choices=[('ORTOPEDIA', 'ORTOPEDIA'), ('ORTODONCIA', 'ORTODONCIA'), ('GENERAL', 'GENERAL')], max_length=15, null=True)),
                ('user_calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('matricula', models.CharField(blank=True, help_text='solo numeros', max_length=8, primary_key=True, serialize=False)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
            options={
                'verbose_name': 'Nucleo',
                'verbose_name_plural': 'Nucleos',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_nucleo', models.CharField(choices=[('CONYUGE', 'CONYUGE'), ('MADRE', 'MADRE'), ('PADRE', 'PADRE'), ('HIJO', 'HIJO')], default='', max_length=12)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.nucleo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('titulo', models.CharField(default='', max_length=125, verbose_name='Titulo')),
                ('contenido', models.TextField(default='', verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='upload/imagenesConsulta', verbose_name='Imagen')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_trat_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
            options={
                'db_table': 'ImgConsultas',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion_dental', models.CharField(blank=True, max_length=50, null=True)),
                ('test_dental', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trat_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='AntecedentesClinicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumador', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Tabaco')),
                ('coproparasitario', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Coproparasitario')),
                ('aparato_digestivo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Ap.Digestivo')),
                ('alergias', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Alergias')),
                ('oncologicas', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Oncologicas')),
                ('autoinmnunes', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Autoinmunes')),
                ('intervenciones', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=2, verbose_name='Intervenciones')),
                ('endocrinometabólico', models.CharField(choices=[('DIABETES', 'DIABETES'), ('TIROIDES', 'TIROIDES'), ('DISPLEMIAS BAJO TRATAMIENTO', 'Infarto Agudo de Miocardio')], default='', max_length=27, verbose_name='Endocrinometabólico')),
                ('cardiovascular', models.CharField(choices=[('H.T.A.', 'HIPERTENSION'), ('ARRITMIAS', 'ARRITMIAS'), ('I.A.M', 'INFARTO MIOCARDIO'), ('OTROS', 'OTROS')], default='', max_length=27, verbose_name='Cardiovascular')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.paciente')),
            ],
        ),
    ]
