# Generated by Django 3.1.1 on 2020-09-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20200916_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='titulo',
        ),
    ]
