# Generated by Django 3.1.1 on 2020-09-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='descripcion',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='test_dental',
            new_name='indicaciones',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='posicion_dental',
            new_name='tratamiento',
        ),
    ]
