# Generated by Django 3.1.1 on 2020-09-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalE', '0003_remove_consulta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='indicaciones',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.CharField(default='', max_length=250),
        ),
    ]
